spring:
  config:
    activate:
      on-profile: test
  jpa:
    show-sql: false
  docker:
    compose:
      enabled: false
  rabbitmq:
    listener:
      simple:
        auto-startup: false

logging:
  level:
    com.facecheck: DEBUG
